## [과제 1]

### 다음과 같이 변수를 생성하였습니다.
### 다음 문제를 풀어주세요.

In [0]:
rep1 = 11
rep2 = 3
rep3 = "서울시 부동산 매매추이"
rep4 = [2,4,7,8,10]
rep5 = {"grape":"포도", "melon":"메론", "apple":"사과", "banana":"오렌지"}

####1) 변수 rep5의 형태를 확인해주세요.

In [11]:
type(rep5)

dict

####2) 변수 rep1을 변수 rep2로 나누었을 때 몫과 나머지를 구해주세요.

In [13]:
rep1 // rep2

3

In [14]:
rep1 % rep2

2

####3) 변수 rep3를 띄어쓰기를 기준으로 분리해서 리스트로 만들어주세요.

In [220]:
rep3.split()

['서울시', '부동산', '매매추이']

####4) 리스트 rep4의 3번째 값인 7을 6으로 수정해주세요

In [16]:
rep4[2]=6
rep4

[2, 4, 6, 8, 10]

####5) 딕셔너리 rep5에서 banana의 값을 바나나로 수정하고, orange를 추가해주세요.

In [17]:
rep5["banana"]="바나나"
rep5["orange"]="오렌지"
rep5

{'apple': '사과', 'banana': '바나나', 'grape': '포도', 'melon': '메론', 'orange': '오렌지'}

##파일 불러오기

In [127]:
from google.colab import files
uploaded = files.upload()

MessageError: ignored

In [207]:
import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['apart_dealing.csv'].decode('cp949')))
df

                 시군구       번지   본번  부번  ... 거래금액(만원)   층  건축년도       도로명
0      서울특별시 강남구 개포동    655-2  655   2  ...  134,500   4  1988       언주로
1      서울특별시 강남구 개포동    658-1  658   1  ...  160,000   4  1987       언주로
2      서울특별시 강남구 개포동    658-1  658   1  ...  160,000   5  1987       언주로
3      서울특별시 강남구 개포동    658-1  658   1  ...  124,000   4  1987       언주로
4      서울특별시 강남구 개포동    658-1  658   1  ...  141,000   5  1987       언주로
5      서울특별시 강남구 개포동      652  652   0  ...  170,000  10  1984       개포로
6      서울특별시 강남구 개포동      652  652   0  ...  165,000  12  1984       개포로
7      서울특별시 강남구 개포동      652  652   0  ...  240,000  15  1984       개포로
8      서울특별시 강남구 개포동      652  652   0  ...  197,000  12  1984       개포로
9      서울특별시 강남구 개포동      652  652   0  ...  157,000   6  1984       개포로
10     서울특별시 강남구 개포동  12월 02일   12   2  ...  175,000   8  2004   개포로109길
11     서울특별시 강남구 개포동  12월 02일   12   2  ...  200,000  12  2004   개포로109길
12     서울특별시 강남구 개포동  12월 02일   12   2  ...  179,000  21  2004   개포로109길
13     서울특별시 강남구 개포동  12월 02일   12   2  ...  211,000  14  2004   개포로109길
14     서울특별시 강남구 개포동  12월 02일   12   2  ...  174,000  16  2004   개포로109길
15     서울특별시 강남구 개포동      141  141   0  ...  166,000   3  1982       개포로
16     서울특별시 강남구 개포동      141  141   0  ...  166,500   2  1982       개포로
17     서울특별시 강남구 개포동      141  141   0  ...  167,000   5  1982       개포로
18     서울특별시 강남구 개포동      141  141   0  ...  150,000   3  1982       개포로
19     서울특별시 강남구 개포동      141  141   0  ...  207,000   3  1982       선릉로
20     서울특별시 강남구 개포동      141  141   0  ...  151,000   3  1982       개포로
21     서울특별시 강남구 개포동      141  141   0  ...  260,000   5  1982       개포로
22     서울특별시 강남구 개포동      141  141   0  ...  199,500   3  1982       선릉로
23     서울특별시 강남구 개포동      141  141   0  ...  171,000   2  1982       개포로
24     서울특별시 강남구 개포동      141  141   0  ...  220,000   2  1982       선릉로
25     서울특별시 강남구 개포동      141  141   0  ...  186,500   2  1982       개포로
26     서울특별시 강남구 개포동      141  141   0  ...  188,000   4  1982       선릉로
27     서울특별시 강남구 개포동      141  141   0  ...  210,000   1  1982       개포로
28     서울특별시 강남구 개포동      141  141   0  ...  160,000   2  1982       개포로
29     서울특별시 강남구 개포동      141  141   0  ...  193,000   5  1982       개포로
...              ...      ...  ...  ..  ...      ...  ..   ...       ...
52022  서울특별시 중랑구 중화동      450  450   0  ...   42,000  18  1997       동일로
52023  서울특별시 중랑구 중화동      450  450   0  ...   44,900  19  1997       동일로
52024  서울특별시 중랑구 중화동      450  450   0  ...   53,700  20  1997       동일로
52025  서울특별시 중랑구 중화동      450  450   0  ...   50,000  27  1997       동일로
52026  서울특별시 중랑구 중화동      450  450   0  ...   54,000  10  1997       동일로
52027  서울특별시 중랑구 중화동      450  450   0  ...   43,300  19  1997       동일로
52028  서울특별시 중랑구 중화동      450  450   0  ...   43,300  23  1997       동일로
52029  서울특별시 중랑구 중화동      450  450   0  ...   51,000   2  1997       동일로
52030  서울특별시 중랑구 중화동      450  450   0  ...   43,900  18  1997       동일로
52031  서울특별시 중랑구 중화동      450  450   0  ...   41,500  16  1997       동일로
52032  서울특별시 중랑구 중화동      450  450   0  ...   37,800  13  1997       동일로
52033  서울특별시 중랑구 중화동      450  450   0  ...   45,900  22  1997       동일로
52034  서울특별시 중랑구 중화동      450  450   0  ...   51,500  12  1998       동일로
52035  서울특별시 중랑구 중화동      450  450   0  ...   40,000  17  1998       동일로
52036  서울특별시 중랑구 중화동      450  450   0  ...   39,000   7  1998       동일로
52037  서울특별시 중랑구 중화동      450  450   0  ...   42,900  26  1998       동일로
52038  서울특별시 중랑구 중화동      450  450   0  ...   54,400   6  1998       동일로
52039  서울특별시 중랑구 중화동      450  450   0  ...   43,500  18  1998       동일로
52040  서울특별시 중랑구 중화동      450  450   0  ...   41,300   5  1998       동일로
52041  서울특별시 중랑구 중화동      450  450   0  ...   55,500   8  1998       동일로
52042  서울특별시 중랑구 중화동      450  450   0  ...   55,800  20  1998       동일로
52043  서울특별시 중랑구 중화동   274-51  274  51  ...   34,000   4  2003   동일로144길
52044  서울특별시 중랑구 중화동   274-75  274  75  ...   27,500   2  2003   동일로144길
52045  서울특별시 중랑구 중화동   274-75  274  75  ...   25,800   6  2003   동일로144길
52046  서울특별시 중랑구 중화동   274-76  274  76  ...   29,500   4  2003   동일로144길
52047  서울특별시 중랑구 중화동   274-76  274  76  ...   21,000   5  2003   동일로144길
52048  서울특별시 중랑구 중화동   274-76  274  76  ...   29,500   3  2003   동일로144길
52049  서울특별시 중랑구 중화동   274-76  274  76  ...   30,000   5  2003   동일로144길
52050  서울특별시 중랑구 중화동   274-77  274  77  ...   24,500   2  2003   동일로144길
52051  서울특별시 중랑구 중화동       11   11   0  ...   34,500   7  2007  봉화산로27가길

[52052 rows x 12 columns]

## [과제 3]

### 단지명, 전용면적, 거래금액 컬럼만 보여주세요

In [208]:
df[["단지명","전용면적(㎡)","거래금액(만원)"]].head(10)

              단지명  전용면적(㎡) 거래금액(만원)
0  개포2차현대아파트(220)    77.75  134,500
1  개포6차우성아파트1동~8동    79.97  160,000
2  개포6차우성아파트1동~8동    79.97  160,000
3  개포6차우성아파트1동~8동    67.28  124,000
4  개포6차우성아파트1동~8동    79.97  141,000
5          개포우성3차   104.43  170,000
6          개포우성3차   104.43  165,000
7          개포우성3차   161.00  240,000
8          개포우성3차   133.46  197,000
9          개포우성3차   104.43  157,000

##[과제 4]
### 아래와 같은 조건에 따라 '규모' 이라는 새로운 컬럼을 만들어 주세요.
#### 전용면적 60㎡이하 - 소형
#### 전용면적 60㎡초과 85㎡이하 - 중형
#### 전용면적 85㎡초과 102㎡이하 - 중대형
#### 전용면적 102㎡초과 - 대형

In [209]:
df.loc[df["전용면적(㎡)"]<=60, '규모']="소형"
df.loc[(df["전용면적(㎡)"]>60) & (df["전용면적(㎡)"]<=85), '규모']="중형"
df.loc[(df["전용면적(㎡)"]>85) & (df["전용면적(㎡)"]<=102), '규모']="중대형"
df.loc[df["전용면적(㎡)"]>102, '규모']="대형"
df.head()

             시군구     번지   본번  부번             단지명  ...  거래금액(만원)  층  건축년도  도로명  규모
0  서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)  ...   134,500  4  1988  언주로  중형
1  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   160,000  4  1987  언주로  중형
2  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   160,000  5  1987  언주로  중형
3  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   124,000  4  1987  언주로  중형
4  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   141,000  5  1987  언주로  중형

[5 rows x 13 columns]

##[과제 5]
### 1) '계약년월' 컬럼의 데이터와 '계약일' 컬럼의 데이터를 합쳐서 '계약일' 컬럼으로 만들고, 날짜 타입으로 변환해주세요.

In [210]:
df["계약일"]=df["계약년월"].astype('str') + df["계약일"].astype('str')
df['계약일'] = pd.to_datetime(df['계약일'], format='%Y%m%d')
df.head()

             시군구     번지   본번  부번             단지명  ...  거래금액(만원)  층  건축년도  도로명  규모
0  서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)  ...   134,500  4  1988  언주로  중형
1  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   160,000  4  1987  언주로  중형
2  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   160,000  5  1987  언주로  중형
3  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   124,000  4  1987  언주로  중형
4  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...   141,000  5  1987  언주로  중형

[5 rows x 13 columns]

### 2) 계약일 기준으로 내림차순으로 정렬해주세요.

In [211]:
df.sort_values("계약일", ascending=False).head()

                 시군구    번지    본번  부번  ...   층  건축년도      도로명  규모
44116  서울특별시 양천구 신정동  1323  1323   0  ...   5  2016   중앙로36길  중형
19065  서울특별시 노원구 상계동  1255  1255   0  ...  12  1998  동일로245길  소형
22216  서울특별시 도봉구 도봉동   641   641   0  ...  17  1996      마들로  소형
22387  서울특별시 도봉구 도봉동   657   657   0  ...  12  2010      마들로  대형
36118  서울특별시 성북구 돈암동   524   524   0  ...   5  2005     아리랑로  대형

[5 rows x 13 columns]

##[과제 6]
#### 1) '거래금액(만원)' 컬럼을 float 형태로 변환해주세요.
##### 힌트) 쉼표를 없애주어야 변환이 가능합니다.

In [213]:
df['거래금액(만원)'] = df['거래금액(만원)'].apply(lambda e: e.split(",")[0]+e.split(",")[1])
df['거래금액(만원)'] = df['거래금액(만원)'].convert_objects(convert_numeric=True)
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

                 시군구       번지   본번  부번  ...   층  건축년도       도로명  규모
0      서울특별시 강남구 개포동    655-2  655   2  ...   4  1988       언주로  중형
1      서울특별시 강남구 개포동    658-1  658   1  ...   4  1987       언주로  중형
2      서울특별시 강남구 개포동    658-1  658   1  ...   5  1987       언주로  중형
3      서울특별시 강남구 개포동    658-1  658   1  ...   4  1987       언주로  중형
4      서울특별시 강남구 개포동    658-1  658   1  ...   5  1987       언주로  중형
5      서울특별시 강남구 개포동      652  652   0  ...  10  1984       개포로  대형
6      서울특별시 강남구 개포동      652  652   0  ...  12  1984       개포로  대형
7      서울특별시 강남구 개포동      652  652   0  ...  15  1984       개포로  대형
8      서울특별시 강남구 개포동      652  652   0  ...  12  1984       개포로  대형
9      서울특별시 강남구 개포동      652  652   0  ...   6  1984       개포로  대형
10     서울특별시 강남구 개포동  12월 02일   12   2  ...   8  2004   개포로109길  대형
11     서울특별시 강남구 개포동  12월 02일   12   2  ...  12  2004   개포로109길  대형
12     서울특별시 강남구 개포동  12월 02일   12   2  ...  21  2004   개포로109길  대형
13     서울특별시 강남구 개포동  12월 02일   12   2  ...  14  2004   개포로109길  대형
14     서울특별시 강남구 개포동  12월 02일   12   2  ...  16  2004   개포로109길  대형
15     서울특별시 강남구 개포동      141  141   0  ...   3  1982       개포로  소형
16     서울특별시 강남구 개포동      141  141   0  ...   2  1982       개포로  소형
17     서울특별시 강남구 개포동      141  141   0  ...   5  1982       개포로  소형
18     서울특별시 강남구 개포동      141  141   0  ...   3  1982       개포로  소형
19     서울특별시 강남구 개포동      141  141   0  ...   3  1982       선릉로  소형
20     서울특별시 강남구 개포동      141  141   0  ...   3  1982       개포로  소형
21     서울특별시 강남구 개포동      141  141   0  ...   5  1982       개포로  소형
22     서울특별시 강남구 개포동      141  141   0  ...   3  1982       선릉로  소형
23     서울특별시 강남구 개포동      141  141   0  ...   2  1982       개포로  소형
24     서울특별시 강남구 개포동      141  141   0  ...   2  1982       선릉로  중형
25     서울특별시 강남구 개포동      141  141   0  ...   2  1982       개포로  소형
26     서울특별시 강남구 개포동      141  141   0  ...   4  1982       선릉로  소형
27     서울특별시 강남구 개포동      141  141   0  ...   1  1982       개포로  소형
28     서울특별시 강남구 개포동      141  141   0  ...   2  1982       개포로  소형
29     서울특별시 강남구 개포동      141  141   0  ...   5  1982       개포로  소형
...              ...      ...  ...  ..  ...  ..   ...       ...  ..
52022  서울특별시 중랑구 중화동      450  450   0  ...  18  1997       동일로  소형
52023  서울특별시 중랑구 중화동      450  450   0  ...  19  1997       동일로  소형
52024  서울특별시 중랑구 중화동      450  450   0  ...  20  1997       동일로  중형
52025  서울특별시 중랑구 중화동      450  450   0  ...  27  1997       동일로  중형
52026  서울특별시 중랑구 중화동      450  450   0  ...  10  1997       동일로  중형
52027  서울특별시 중랑구 중화동      450  450   0  ...  19  1997       동일로  소형
52028  서울특별시 중랑구 중화동      450  450   0  ...  23  1997       동일로  소형
52029  서울특별시 중랑구 중화동      450  450   0  ...   2  1997       동일로  중형
52030  서울특별시 중랑구 중화동      450  450   0  ...  18  1997       동일로  소형
52031  서울특별시 중랑구 중화동      450  450   0  ...  16  1997       동일로  소형
52032  서울특별시 중랑구 중화동      450  450   0  ...  13  1997       동일로  소형
52033  서울특별시 중랑구 중화동      450  450   0  ...  22  1997       동일로  소형
52034  서울특별시 중랑구 중화동      450  450   0  ...  12  1998       동일로  중형
52035  서울특별시 중랑구 중화동      450  450   0  ...  17  1998       동일로  소형
52036  서울특별시 중랑구 중화동      450  450   0  ...   7  1998       동일로  소형
52037  서울특별시 중랑구 중화동      450  450   0  ...  26  1998       동일로  소형
52038  서울특별시 중랑구 중화동      450  450   0  ...   6  1998       동일로  중형
52039  서울특별시 중랑구 중화동      450  450   0  ...  18  1998       동일로  소형
52040  서울특별시 중랑구 중화동      450  450   0  ...   5  1998       동일로  소형
52041  서울특별시 중랑구 중화동      450  450   0  ...   8  1998       동일로  중형
52042  서울특별시 중랑구 중화동      450  450   0  ...  20  1998       동일로  중형
52043  서울특별시 중랑구 중화동   274-51  274  51  ...   4  2003   동일로144길  중형
52044  서울특별시 중랑구 중화동   274-75  274  75  ...   2  2003   동일로144길  중형
52045  서울특별시 중랑구 중화동   274-75  274  75  ...   6  2003   동일로144길  소형
52046  서울특별시 중랑구 중화동   274-76  274  76  ...   4  2003   동일로144길  중형
52047  서울특별시 중랑구 중화동   274-76  274  76  ...   5  2003   동일로144길  소형
52048  서울특별시 중랑구 중화동   274-76  274  76  ...   3  2003   동일로144길  중형
52049  서울특별시 중랑구 중화동   274-76  274  76  ...   5  2003   동일로144길  중형
52050  서울특별시 중랑구 중화동   274-77  274  77  ...   2  2003   동일로144길  중형
52051  서울특별시 중랑구 중화동       11   11   0  ...   7  2007  봉화산로27가길  중형

[52052 rows x 13 columns]

#### 2) '시군구' 컬럼의 데이터를 '시' 컬럼, '군'컬럼, '동'컬럼으로 분리해서 만들어 주세요

In [214]:
df['시']=df["시군구"].apply(lambda e: e.split()[0])
df['구']=df["시군구"].apply(lambda e: e.split()[1])
df['동']=df["시군구"].apply(lambda e: e.split()[2])
df.head()

             시군구     번지   본번  부번             단지명  ...  도로명  규모      시    구    동
0  서울특별시 강남구 개포동  655-2  655   2  개포2차현대아파트(220)  ...  언주로  중형  서울특별시  강남구  개포동
1  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...  언주로  중형  서울특별시  강남구  개포동
2  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...  언주로  중형  서울특별시  강남구  개포동
3  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...  언주로  중형  서울특별시  강남구  개포동
4  서울특별시 강남구 개포동  658-1  658   1  개포6차우성아파트1동~8동  ...  언주로  중형  서울특별시  강남구  개포동

[5 rows x 16 columns]

#### 3) 가락동의 중형아파트의 평균 거래금액은 얼마인가요?"

In [215]:
a=df[(df['동']=='가락동') & (df["규모"]=='중형')]
a['거래금액(만원)'].mean()

83827.90697674418

#### 4) 5층이하인 등촌동의 중대형아파트의 단지명, 계약일, 거래금액 정보를 알려주세요.

In [223]:
b=df[(df['동']=='가락동') & (df["규모"]=='중형') & (df["층"]<=5)]
b[["단지명","계약일","거래금액(만원)"]]

                         단지명        계약일  거래금액(만원)
37979            가락(1차)쌍용아파트 2018-08-11     82000
37991            가락(1차)쌍용아파트 2018-08-20     79800
37997            가락(1차)쌍용아파트 2018-08-23     79900
38001            가락(1차)쌍용아파트 2018-08-25     81000
38013            가락(1차)쌍용아파트 2018-08-30     85000
38015            가락(1차)쌍용아파트 2018-08-31     86000
38022            가락(1차)쌍용아파트 2018-09-03     83500
38023            가락(1차)쌍용아파트 2018-09-03     85000
38025            가락(1차)쌍용아파트 2018-09-05     83000
38028            가락(1차)쌍용아파트 2018-09-10     89900
38060            가락(1차)쌍용아파트 2019-05-14     80600
38061            가락(1차)쌍용아파트 2019-05-21     80500
38068            가락(1차)쌍용아파트 2019-06-01     84800
38079            가락(1차)쌍용아파트 2019-06-21     85700
38094            가락(1차)쌍용아파트 2019-07-08     81000
38095            가락(1차)쌍용아파트 2019-07-09     87500
38097            가락(1차)쌍용아파트 2019-07-12     87500
38105  가락3차쌍용스윗닷홈 101동, 102동 2019-02-12     82000
38108       가락3차쌍용스윗닷홈(103동) 2019-06-25     77500
38109       가락3차쌍용스윗닷홈(103동) 2019-06-25     77500
38110       가락3차쌍용스윗닷홈(103동) 2019-06-26     85000
38111       가락3차쌍용스윗닷홈(103동) 2019-07-08     88000
38118                가락금호아파트 2018-08-11     85000
38126                가락금호아파트 2018-08-27     83500
38153                가락미륭아파트 2018-08-06     70000
38158                가락미륭아파트 2018-08-25     82000
38159                가락미륭아파트 2018-09-01     75000
38166                가락미륭아파트 2019-06-24     82800
38170                가락스타클래스 2019-07-07     80000
38172               가락쌍용(2차) 2018-08-06     75000
...                      ...        ...       ...
38401               송파동부쎈트레빌 2019-06-17     89900
38403                 쌍용노블래스 2018-09-04     50000
38404                 쌍용노블래스 2018-09-13     46500
38407                 에스디펠리체 2019-01-24     46500
38445                  우정에쉐르 2019-03-26     51300
38447                  주성파크빌 2018-10-13     54700
38448                  주성파크빌 2018-10-24     43000
38449                  주성파크빌 2019-05-28     40000
38454                    풍림1 2018-09-08     64500
38455                    풍림1 2019-03-27     55000
38458                    프라자 2018-08-09     79000
38459                    프라자 2018-08-13     84000
38462                    프라자 2018-08-23     87500
38463                    프라자 2018-08-23     87000
38471                    프라자 2019-02-23     81500
38472                    프라자 2019-03-06     82000
38473                    프라자 2019-05-11     85800
38474                    프라자 2019-05-13     80000
38479                    한신1 2018-08-09     67000
38482                    한신1 2018-08-27     66000
38484                    한신1 2018-09-06     77000
38501                 현대(5차) 2018-08-22     93000
38506                현대(60동) 2018-08-06     79500
38507                현대(60동) 2019-03-01     77000
38508                 현대(6차) 2018-08-14     69800
38509                 현대(6차) 2018-09-08     77000
38510                 현대(6차) 2018-09-09     78000
38514                    현대7 2018-08-13     67000
38515                    현대7 2018-08-24     65000
38517                    현대7 2019-07-16     72000

[95 rows x 3 columns]